name: Deploy to Windows Server

on:
  push:
    branches: [ main ]

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          python -m PyInstaller --onefile --windowed `
            --add-data "src/config.json;." `
            src/AppBootLaunch.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: BootUpLauncher
          path: dist/AppBootLaunch.exe