name: Deploy to Windows Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Build EXE
        run: pyinstaller --onefile --windowed src/AppBootLaunch.py

      - name: Copy to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: dist/AppBootLaunch.exe
          target: C:/Deployments/AppBootLaunch.exe

      - name: Register on Startup via PowerShell Remoting
        run: |
          $session = New-PSSession -HostName $Env:SERVER_HOST -UserName $Env:SERVER_USER -KeyFilePath $Env:SERVER_SSH_KEY
          Invoke-Command -Session $session -ScriptBlock {
            $exe = 'C:\Deployments\AppBootLaunch.exe'
            Set-ItemProperty -Path HKLM:\Software\Microsoft\Windows\CurrentVersion\Run `
                             -Name 'AppBootLaunch' -Value $exe
          }
        shell: pwsh
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
